### ISSUE TITLE
Developer comfort

### ISSUE THREAD

**Issue by Ralim** [pine64/OpenPineBuds#30]
Hia,

Two things I would like to do to cleanup this code base for easier work going forward:

## 1 - Code Format rule

I would like to add a `.clang-format` rule to try and keep all code formatted the same.
I prefer the LLVM rules; but wnat to know what others think?

Anyone have any reasons against this?

## 2 - Cleaning up

There is a bunch of cruft in here we cant use on the Pinebuds such as USB.
What are thoughts on removing things we just cant physically use (USB, I2C, SDMCC drivers for example).

**Comment by lizz-34** [comment]
> 2 - Cleaning up
> 
> There is a bunch of cruft in here we cant use on the Pinebuds such as USB.
What are thoughts on removing things we just cant physically use (USB, I2C, SDMCC drivers for example).

I think cleaning should be done with keeping mind that this firmware will become more "universal" one day. Of course, in embedded devices and firmwares it isn't possible at the level of PCs, for example, but things can still be done in universal, standard way so that the same code works with small changes on many devices.

**Comment by ThatcherC** [comment]
A Clang format pass would be great! We could plug that into the CI too to maintain consistency over time. I like the looks of the LLVM style personally.

**Comment by Ralim** [comment]
@lizz-34 

I guess this is the question we have to ask really.
Is this firmware absolutely going to be used in other designs that are not earbuds?

My thought is that if we need a file we can always bring it back from git history; and we would gain readability by not having code that we can't use around (and polluting search).

My feeling is that we should start to refactor to make it our own; by doing things like cleaning up code we can't use for this application and starting to expand out adding our own code.

For example I would like to split up the main file to move button handling away from the main loop so it's not buried in these insanely long files.

I don't think we need to be hyper careful keeping things we can't use in an earbud application; knowing we always have the backup of git and the raw blob from the wiki to look back to should we need to.

If you wanted I could make a branch before the cleanups to make it easier to revert to ?


@ThatcherC 

I agree, a CI check is a good idea.

I'll have a poke at adding it to the makefile when I get a chance.

**Comment by lizz-34** [comment]
>I guess this is the question we have to ask really.
>Is this firmware absolutely going to be used in other designs that are not earbuds?

Because it isn't possible to make a good universal firmware to all devices, like Linux (software, not firmware) is on PC, we should target this to something, your work IronOS is a good example of this. I think the that focus is speakers, headphones and earbuds, nothing more and nothing less. And that's why I say that when removing things, it's worth keeping in mind that we're aiming for something (speaker, headphones, earbuds) "universal". In fact, IronOS does this too. It works on Pinecil and [this](https://www.miniware.com.cn/product/mhp30-mini-hot-plate-preheater/) (according to the README, I don't know much about this firmware).

> I don't think we need to be hyper careful keeping things we can't use in an earbud application; knowing we always have the backup of git and the raw blob from the wiki to look back to should we need to.

How does a raw blob of the pre-installed closed source, obfuscated binary relate to this?

**Comment by Ralim** [comment]
>target this to something

Yep this is exactly what I'm thinking. So if we take our target as generally being a device that does Bluetooth -> Speaker actions it means we can probably trim all the fat for things like SD card support and USB. (USB I could see arguements both ways on, but given its a large blob prefer drop for now and revive if required)

>How does a raw blob of the pre-installed closed source, obfuscated binary relate to this?

It doesnt; by blob I meant the archive that we used to initally start this repository

**Comment by lizz-34** [comment]
> Yep this is exactly what I'm thinking. So if we take our target as generally being a device that does Bluetooth -> Speaker actions it means we can probably trim all the fat for things like SD card support and USB. (USB I could see arguements both ways on, but given its a large blob prefer drop for now and revive if required)

Often non-wireless speakers, headphones and earbuds don't have firmware or smart. They are only analog. However, there are some wired ones with firmware and smart. That's why I don't think Bluetooth should be a requirement. 

You do need USB in almost every portable speaker, headphone and wireless earbuds (non-true wireless). We can find a use for the SD card in some speakers. Anyway, deleting them is fine for me (as you said, we can revive them), but I think it was good to bring up in this discussion that we should think carefully when we delete things.

> It doesnt; by blob I meant the archive that we used to initally start this repository

Ok, I don't think it's a blob, thanks for the clarification.

**Comment by WebWire-NL** [comment]
I think the idea on cleaning up as much as possible and code by a standard would attract more developers, as the source code would be more understandable so beginners don't get lost in the maze of unused code, great idea! Maybe even the NFC part, wonder if someone will ever use it because like delivered from stock with the charging case is just working well, we also need the case to flash the firmware. This code has a big history based on older chip's which were released and improved also so it's just a snapshot from the bes2000 SDK. On the other side it would be harder to find related code so keeping a branch with the original firmware would be a nice idea.

**Comment by lizz-34** [comment]
> Maybe even the NFC part

Does PineBuds Pro have NFC? Or is it just useless code?

> because like delivered from stock with the charging case is just working well

What do you mean?

> we also need the case to flash the firmware.

What do you mean?

**Comment by WebWire-NL** [comment]
> > Maybe even the NFC part
> 
> Does PineBuds Pro have NFC? Or is it just useless code?
Sorry i meant Wireless charging, it's a SoC, System on Chip (a design that combines many or all high-level function elements of an electronic device onto a single chip instead of using separate components mounted to a motherboard)
If you soldier the right components to the right pin's on the buds you could charge them wirelessly, but unless a lot of people will risk broken buds and want take all the effort while you can just charge them in the case i wouldn't see any use.
A quick look in the code just suggests it's a chip feature and no code is needed, just components but i can imagine there's a lot of code which is not being used.
> > because like delivered from stock with the charging case is just working well
You can charge the buds in the case instead of adding components to the buds to charge them wireless.
> What do you mean?
> 
> > we also need the case to flash the firmware.
I prefer UART, it's a reliable method for flashing.
> What do you mean?

**Comment by WebWire-NL** [comment]
> > Maybe even the NFC part
> 
> Does PineBuds Pro have NFC? Or is it just useless code?
> 
> > because like delivered from stock with the charging case is just working well
> 
> What do you mean?
> 
> > we also need the case to flash the firmware.
> 
> What do you mean?

I prefer UART, it's a reliable method for flashing.

**Comment by WebWire-NL** [comment]
Sorry by NFC i meant wireless charging, you could add it but a quick look at the code tells me it seems no code is needed, i wonder how many people are willing to brick their device for wireless charging. But there is a lot of unneeded code.
The charging case provides us with charging and UART to flash, a proven reliable method which has been used for ages. But still it's debatable to remove the code if not needed and OTA seems to be reliable.

**Comment by lizz-34** [comment]
> Sorry by NFC i meant wireless charging

That explains :D

>  you could add it but a quick look at the code tells me it seems no code is needed

I know, I wrote about it to the [PineBuds Pro wiki page](https://wiki.pine64.org/wiki/PineBuds_Pro#Wireless_charging). No code is needed? Then why here is code for it if it's useless?

> i wonder how many people are willing to brick their device for wireless charging

To brick the device? Wireless charging doesn't brick the device. Why it does?

> But still it's debatable to remove the code if not needed and OTA seems to be reliable.

What are you trying to say?

**Comment by Ralim** [comment]
>To brick the device? Wireless charging doesn't brick the device. Why it does?

I would take a punt and guess that vast majority are not up for the SMD soldering required to add the wireless charging to the case.


>But still it's debatable to remove the code if not needed and OTA seems to be reliable.

The code has fragments to let one do firmware updates over bluetooth. But it adds a lot of complexity (and requires an app for all devices that can do it).

For now I'll probably leave the fragments there; but I doubt it will get used. If no progress on it in a while we could consider trimming it to noticeably reduce build complexity.


In terms of the original issue #33 resolves (1).

Going to merge it later tonight if no complaints. Then Ill make a branch to preserve that point in time.
Then start cleanup
